### ISSUE TITLE
android:allowBackup="true" attribute in Manifest causes problems

### ISSUE THREAD

**Issue by jguerinet** [hypertrack/hyperlog-android#1]
Hi, 

Looks like you have the above attribute in the AndroidManifest. This causes merging problems for those who have apps with `allowBackup` set to false. There's a way to get around it using `tools:replace` but I'm wondering if there's a need for it on your side (since using `tools:replace` effectively ignores it regardless)?

I can quickly open up a PR if needed. 

Thanks, 
Julien

**Comment by amanjain08** [comment]
Fix in this commit https://github.com/hypertrack/hyperlog-android/commit/fc653b97083026e283c3e0449f168862b42c8762 .
