### ISSUE TITLE
Version name always returns 1.0

### ISSUE THREAD

**Issue by arokanto** [hypertrack/hyperlog-android#19]
I believe you can't trust `BuildConfig.VERSION_NAME` to return the actual version name defined in build.gradle.

You should maybe update LogFormat to look something like this:

```java
public class LogFormat implements Serializable {

    private String deviceUUID;
    private String versionName;

    public LogFormat(Context context) {
        Context mContext = context.getApplicationContext();
        deviceUUID = Settings.Secure.getString(mContext.getContentResolver(), Settings.Secure.ANDROID_ID);
        try {
            PackageInfo pInfo = context.getPackageManager().getPackageInfo(context.getPackageName(), 0);
            this.version = pInfo.versionName;
        } catch (PackageManager.NameNotFoundException exception) {
            this.version = "null";
        }
}
```

And then use `this.version` when building the log string.

**Comment by leogcurvelo** [comment]
Yeah, I believe BuildConfig.VERSION_NAME always returns the version of the HyperLog library, instead of the version of the app.

https://github.com/hypertrack/hyperlog-android/blob/a37afa662511c34d742d3372eef726207cfc04ff/hyperlog/build.gradle#L36

**Comment by arokanto** [comment]
Ah, I must've misunderstood that. Anyway, getting the app version easily to logs is probably a common need, so implementing something like that might be a good idea in the future.

Thanks!

**Comment by leogcurvelo** [comment]
Actually I think logging the App version was the intention of the library author... Doesn't make much sense to log the hyperlog library version.
