### ISSUE TITLE
Log level debug and verbose incorrect when push to server

### ISSUE THREAD

**Issue by timchanyiuman** [hypertrack/hyperlog-android#20]
When use Hyperlog.d or Hyperlog.v to log a message and push to the server, it will use the log level I set globally for level filtering. Other log levels are ok.

**Comment by Adaok** [comment]
Hey @timchanyiuman ! I just saw your issue and the problem, I just push a pull request, fingers crossed for the maintainers read us and merge my little fix. 🤞
